# NUMPY TUTOTIAL

Numpy is a Python package. It stands for 'Numerical Python'. It is a
library consisting of multidimensional array objects and a collection of
routines for processing of array.

In [1]:
import numpy as np
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [2]:
#Let's start first by importing numpy into the kernel.
#Numpy is a python package which stands for Numerical Python.
import numpy as np

a=np.array([1,2,3])
print (a)

[1 2 3]


In [3]:
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [4]:
#1D Array creation
a1=np.array([56,78,34,22])
a1

array([56, 78, 34, 22])

In [5]:
a1.shape

(4,)

In [6]:
p=np.array([[1,2],[3,4]])
p

array([[1, 2],
       [3, 4]])

In [7]:
v=np.array([[70,80],[30,40]])
v

array([[70, 80],
       [30, 40]])

In [8]:
#rows and column
s=np.array([[56,67],[90,45]])
s

array([[56, 67],
       [90, 45]])

In [9]:
s.shape

(2, 2)

In [10]:
m=np.array([[1,2],[3,4],[5,6]])
print(m)
m.shape

[[1 2]
 [3 4]
 [5 6]]


(3, 2)

In [11]:
g=np.array([[4,6,],[8,3,],[9,5]])
g

array([[4, 6],
       [8, 3],
       [9, 5]])

In [12]:
g.shape

(3, 2)

In [13]:
g.reshape(2,3)

array([[4, 6, 8],
       [3, 9, 5]])

In [14]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [15]:
b=np.array([[78,90],[22,33]])
b

array([[78, 90],
       [22, 33]])

In [16]:
b.min()

22

In [17]:
b.shape

(2, 2)

In [18]:
a=np.array([[1,2,],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
a.shape

(3, 2)

In [20]:
a=np.array([[4,5,6],[6,7,8],[3,7,9]])
a

array([[4, 5, 6],
       [6, 7, 8],
       [3, 7, 9]])

In [21]:
# task write numpy array of  shape  4 rows  3 columns
#
#hint   p= np.array([,,],[,,],[,,],[,,])
             # p.shape

In [22]:
# gives shape in dimension :rows and columns
a.shape

(3, 3)

In [23]:
#gives the count of number of elements
a.size

9

In [24]:
# gives the number of bytes/memory accupied by each element
a.itemsize

4

In [25]:
# gives the datatype
a.dtype

dtype('int32')

In [26]:
a.min()

3

In [27]:
a.max()

9

In [28]:
# gives the memory address
a.data

In [29]:
a=np.array([[1,2],[3,4,],[5,6]],dtype='float64')
#c1=np.array([[1,2],[3,4,],[5,6]])

a
#c1

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [30]:
# gives number of bytes  : it is float datatype hence it takes 8 bytes to store the data
a.itemsize

8

In [31]:
a.shape

(3, 2)

In [32]:
a.reshape(2,3)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [33]:
x=np.arange(15)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [34]:
y=np.arange(5)
y

array([0, 1, 2, 3, 4])

In [35]:
a=x.reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [36]:
a=x.reshape(5,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [37]:
x=np.arange(25)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [38]:
a=x.reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
a=np.arange(35).reshape(5,7)
a

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [40]:
a.shape

(5, 7)

In [41]:
a.ndim  # 2 stands for rows and columns

2

In [42]:
a.dtype

dtype('int32')

In [43]:
a.itemsize

4

In [44]:
a.size

35

In [45]:
type(a)

numpy.ndarray

In [46]:
b=np.array([6,7,8])
b

array([6, 7, 8])

In [47]:
type(b)

numpy.ndarray

In [48]:
b=np.array([[1.5,2,3],[4,5,6]],dtype='float32')
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]], dtype=float32)

In [49]:
ra=np.array([(34,78,89),(22,33,77)])
ra

array([[34, 78, 89],
       [22, 33, 77]])

In [50]:
# Ravel  operation where you can convert one numpy array into a single row i.e ravel
print(ra.ravel())

[34 78 89 22 33 77]


In [51]:
b=np.array([(1.5,2,3),(4,5,6)],dtype='int32')
b

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [53]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [54]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [55]:
np.ones((2,3,4), dtype=np.int32)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [56]:
np.empty((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [57]:
#(start,end,skip or jump)
np.arange(10,30,5)

array([10, 15, 20, 25])

In [58]:
np.arange(10,70,6)

array([10, 16, 22, 28, 34, 40, 46, 52, 58, 64])

In [59]:
import numpy as np
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [60]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [61]:
b=np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [62]:
a=np.array([20,30,40,50])
b=np.arange(4)
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [63]:
c=a-b
print(c)

[20 29 38 47]


In [64]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [65]:
b=np.random.random((2,3))
b

array([[0.6744489 , 0.50893189, 0.72364308],
       [0.56536793, 0.35398172, 0.46449753]])

In [66]:
c=np.ones((2,3))
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [67]:
d=b+c
d

array([[1.6744489 , 1.50893189, 1.72364308],
       [1.56536793, 1.35398172, 1.46449753]])

UNIVERSAL FUNCTIONS:

In [68]:
b=np.arange(3)
b

array([0, 1, 2])

In [69]:
np.exp(b)

array([1.        , 2.71828183, 7.3890561 ])

In [70]:
np.sqrt(b)

array([0.        , 1.        , 1.41421356])

In [71]:
c=np.array((2,1,4))
np.add(b,c)

array([2, 2, 6])

INDEXING,SLICING AND ITERATING

In [72]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
a[2]

2

In [74]:
a[2:5]

array([2, 3, 4])

In [75]:
a[-1]

9

In [76]:
a[-2]

8

In [77]:
a[-3]

7

In [78]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
a[-4:]

array([6, 7, 8, 9])

In [80]:
a[-4:-2]

array([6, 7])

Basic slicing is an extension of Python's basic concept of slicing to n
dimentions. A Python slice object is constructed by giving start,stop, and
step paramenters to the built-in slice function. The slice object is passed
to the array to extract a part of array.

In [81]:
import numpy as np
d1 = np.arange(20)

In [82]:
#an ndarray object is prepared by arange() function.
#Then a slice object is defined with start, stop, and step value 2, 20, and 2 respectively
s = slice(2,20,2)

In [83]:
print(d1[s])

[ 2  4  6  8 10 12 14 16 18]


In [84]:
d2 = np.arange(20)
d2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [85]:
d2[5:] #Slicing from 5th index till end of the array

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [86]:
d3 = np.array([np.nan,1,2,3,np.nan,6,7,8.])

In [87]:
print(d3[~np.isnan(d3)])

[1. 2. 3. 6. 7. 8.]


The random module provides nice functions to generate random numbers (and
also statistical distributions) of any given shape.rand function will generate
any bumber between 0 and 1

In [88]:
np.random.rand(2,2)

array([[0.06845197, 0.24834305],
       [0.64099473, 0.87901821]])

Random willgenerate any number for normal distribution in the given dimension formate

In [89]:
np.random.randn(2,3)

array([[0.31067538, 1.08284789, 1.50254539],
       [0.50190934, 0.78528984, 0.04401732]])