# For Loop --->
for subject in range(5):

Pass exam 5 times

Once for each subject

# While loop --->
while grade !='A':

Keep Repeating untill

Comparison gives a False

In [1]:
marks=50
if marks>60:
    print("Good")
else:
    print("Not Good")

Not Good


In [2]:
Name=input("My Name is ")

My Name is Indresh


In [3]:
Name

'Indresh'

In [4]:
a=[]
for i in range(6,18,2):
    a.append(i)
print(a)

[6, 8, 10, 12, 14, 16]


In [5]:
fruits = ["Apple", "Mango", "Orange", "Banana", "Graps"]
for x in fruits:
  print(x)
  if x == "banana":
    break

Apple
Mango
Orange
Banana
Graps


In [6]:
fruits.append("graps")
fruits

['Apple', 'Mango', 'Orange', 'Banana', 'Graps', 'graps']

In [7]:
fruits.pop(3)
fruits

['Apple', 'Mango', 'Orange', 'Graps', 'graps']

In [8]:
adj = ["red", "big", "tasty"]
fruits = ["apple", "banana", "cherry"]

for x in adj:
  for y in fruits:
    print(x, "==>", y)

red ==> apple
red ==> banana
red ==> cherry
big ==> apple
big ==> banana
big ==> cherry
tasty ==> apple
tasty ==> banana
tasty ==> cherry


In [9]:
fruits.append(adj)
fruits

['apple', 'banana', 'cherry', ['red', 'big', 'tasty']]

In [10]:
fruits.remove(adj)
fruits

['apple', 'banana', 'cherry']

In [11]:
fruits[2] = "orange"
fruits

['apple', 'banana', 'orange']

In [12]:
k=int(input("Value is "))
if k%2==0:
  print("Value of k is",k,"Even Number")
else:
  print("Value of k is",k,"Odd Number")

Value is 10
Value of k is 10 Even Number


In [13]:
name='John'
age=24
print("His name is {} He is {} year old.".format(name,age))

His name is John He is 24 year old.


In [14]:
name = "John"
age = 23
print("%s is %d years old." % (name, age))

John is 23 years old.


In [15]:
k=[40,90,22,78,30,67]
min(k)

22

In [16]:
max(k)

90

In [17]:
def subtraction(a,b):
    sub=a-b
    print(sub)
subtraction(57,94)

-37


In [18]:
def run():
    for x in range(6):
        print(x)
    
run()

0
1
2
3
4
5


In [19]:
def run():
    for x in range(10):
        if x==5:
            return
        print("RUN")

In [20]:
run()

RUN
RUN
RUN
RUN
RUN


In [21]:
def Print():
    for i in range(3):
        print("Python is Awesome")

In [22]:
Print()

Python is Awesome
Python is Awesome
Python is Awesome


In [23]:
a = 25
if a > 15:
    print("Hello")
if a <= 30:
    print("World")
elif a==25:
    print("to")
else:
    print("Python")

Hello
World


In [24]:
def run2():
    for i in range (30):
        if i==15:
            return
        print(i)

In [25]:
run2()

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [26]:
def plus(*args):
    return sum(args)

In [27]:
plus(6,4,10)

20

In [28]:
sum=lambda x,y :x+y;
sum(3,4)

7

In [29]:
def sum (x,y):
    print('addition =',x+y)

In [30]:
sum(7,7)

addition = 14


In [31]:
class myclass:
    k=123
    d=6.7
    def testf():
        print("This is my first class")

In [32]:
m=myclass()
print(m.k)
print(m.d)
m.testf

123
6.7


<bound method myclass.testf of <__main__.myclass object at 0x7fa5758a4890>>

In [33]:
class calculator:
    def addition(a,b):
        return(a+b)
    def division(a,b):
        return(a/b)
    def subtraction(a,b):
        return(a-b)
    def multiply(a,b):
        return(a*b)

In [34]:
calculator.addition(8,8)

16

In [35]:
calculator.division(9,3)

3.0

In [36]:
class employee:
    emp_id=1001
    emp_name="Andrew"
    emp_dept="HR"

In [37]:
class employee:
    emp_id=1001
    emp_name="Andrew"
    emp_dept="HR"
    
    def massage(self):
        return "Employee will join soon"

In [38]:
employee.emp_id

1001

In [39]:
employee.emp_name

'Andrew'

In [40]:
class employee:
    def __init__(self,name,age):
        self.name=name
        self.age=age

In [41]:
p1=employee("Sam",25)
print(p1.name)
print(p1.age)

Sam
25


In [42]:
class company:
    
    def __init__(self,name,location,number_of_employees):
        self.name=name
        self.location=location
        self.number_of_employees=number_of_employees

In [43]:
c=company("George","London",400)
print(c.name)
print(c.location)
print(c.number_of_employees)

George
London
400


In [44]:
class car:
    
    def __init__(self,company,color):
        self.company = company
        self.color = color
        
    def display(self):
        print ('This is a', self.color, self.company)

In [45]:
def main():
    c=car("Ferrari","Red")
    c.display()

In [46]:
if __name__=="__main__":
    main()

This is a Red Ferrari


In [47]:
class employee:
    def __init__(self,name,age):
        print("initializaed method called")
        self.name=name
        self.age=age
        
    def getdata(self,name,age):
        print("getdata method called")
        self.name=name
        self.age=age
        
    def displaydata(self):
        print("Hello",self.name,self.age)

In [48]:
def main():
    e=employee("William",35)
    e.displaydata()
    
    e.getdata("John",25)
    e.displaydata()

In [49]:
if __name__=="__main__":
    main()

initializaed method called
Hello William 35
getdata method called
Hello John 25


In [50]:
class player:
    
    def __init__(self,name,age,sport):
        print("initialized method called")
        self.name=name
        self.age=age
        self.sport=sport
    def getdata(self,name,age,sport):
        print("getdata method called")
        self.name=name
        self.age=age
        self.sport=sport
    def displaydata(self):
        print("Player details:",self.name,self.age,self.sport)
        
def main():
    p=player("Virat",30,"Cricket")
    p.displaydata()
    
    p.getdata("Richard",45,"Tennis")
    p.displaydata()
    
if __name__=="__main__":
    main()

initialized method called
Player details: Virat 30 Cricket
getdata method called
Player details: Richard 45 Tennis


In [51]:
import numpy as np
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [52]:
a.shape

(6,)

In [53]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [55]:
a.itemsize

8

In [56]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [57]:
import pandas as pd
raw_data = {
    'subject_id': ['1', '2', '3', '4', '5'],
    'first_name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayong'],
    'last_name': ['Anderson', 'Ackerman', 'Ali', 'Aoni', 'Atiches']}
df_a = pd.DataFrame(raw_data, columns = ['subject_id', 'first_name', 'last_name'])
df_a

subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5      Ayong   Atiches

In [58]:
raw_data = {
    'subject_id': ['4', '5', '6', '7', '8'],
    'first_name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'],
    'last_name': ['Bonder', 'Black', 'Balwner', 'Brice', 'Btisan']}
df_b = pd.DataFrame(raw_data, columns = ['subject_id', 'first_name', 'last_name'])
df_b

subject_id first_name last_name
0          4      Billy    Bonder
1          5      Brian     Black
2          6       Bran   Balwner
3          7      Bryce     Brice
4          8      Betty    Btisan

In [59]:
df_new = pd.concat([df_a, df_b])
df_new

subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5      Ayong   Atiches
0          4      Billy    Bonder
1          5      Brian     Black
2          6       Bran   Balwner
3          7      Bryce     Brice
4          8      Betty    Btisan

In [60]:
pd.concat([df_a, df_b], axis=1)

subject_id first_name last_name subject_id first_name last_name
0          1       Alex  Anderson          4      Billy    Bonder
1          2        Amy  Ackerman          5      Brian     Black
2          3      Allen       Ali          6       Bran   Balwner
3          4      Alice      Aoni          7      Bryce     Brice
4          5      Ayong   Atiches          8      Betty    Btisan

In [61]:
pd.concat([df_a, df_b], axis=0)

subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5      Ayong   Atiches
0          4      Billy    Bonder
1          5      Brian     Black
2          6       Bran   Balwner
3          7      Bryce     Brice
4          8      Betty    Btisan

In [62]:
raw_data = {
    'subject_id': ['1', '2', '3', '4', '5', '7', '8', '9', '10', '11'],
    'test_id': [51, 15, 15, 61, 16, 14, 15, 1, 61, 16,]}
df_n = pd.DataFrame(raw_data, columns = ['subject_id','test_id'])
df_n

subject_id  test_id
0          1       51
1          2       15
2          3       15
3          4       61
4          5       16
5          7       14
6          8       15
7          9        1
8         10       61
9         11       16

In [63]:
pd.merge(df_new,df_n)

subject_id first_name last_name  test_id
0          1       Alex  Anderson       51
1          2        Amy  Ackerman       15
2          3      Allen       Ali       15
3          4      Alice      Aoni       61
4          4      Billy    Bonder       61
5          5      Ayong   Atiches       16
6          5      Brian     Black       16
7          7      Bryce     Brice       14
8          8      Betty    Btisan       15

In [64]:
pd.merge(df_new, df_n, on='subject_id')

subject_id first_name last_name  test_id
0          1       Alex  Anderson       51
1          2        Amy  Ackerman       15
2          3      Allen       Ali       15
3          4      Alice      Aoni       61
4          4      Billy    Bonder       61
5          5      Ayong   Atiches       16
6          5      Brian     Black       16
7          7      Bryce     Brice       14
8          8      Betty    Btisan       15

In [65]:
#Merge with outer join
#"Full outer join produces the set of all records in table A and table B, with matching records from both sides where available.
#If there is no match, the missing side will contain null."

pd.merge(df_a, df_b, on='subject_id', how='outer')

subject_id first_name_x last_name_x first_name_y last_name_y
0          1         Alex    Anderson          NaN         NaN
1          2          Amy    Ackerman          NaN         NaN
2          3        Allen         Ali          NaN         NaN
3          4        Alice        Aoni        Billy      Bonder
4          5        Ayong     Atiches        Brian       Black
5          6          NaN         NaN         Bran     Balwner
6          7          NaN         NaN        Bryce       Brice
7          8          NaN         NaN        Betty      Btisan

In [66]:
#Merge with inner join
#"Inner join produces only the set of records that match in both table A and B."

pd.merge(df_a, df_b, on='subject_id', how='inner')

subject_id first_name_x last_name_x first_name_y last_name_y
0          4        Alice        Aoni        Billy      Bonder
1          5        Ayong     Atiches        Brian       Black

In [67]:
#It is yet another convenient method to combine two differently indexed dataframes into a single result dataframe.
#This is the "merge" operation, merging the "columns"

#Merge funcion merge only the similar data
import pandas as pd

df1= pd.DataFrame({ "HPI":[80,90,70,60],"Int_Rate":[2,1,2,3],"IND_GDP":[50,45,45,67]}, index=[2001, 2002, 2003, 2004])

df2=pd.DataFrame({ "HPI":[80,90,70,60],"Int_Rate":[2,1,2,3],"IND_GDP":[50,45,45,67]}, index=[2005, 2006, 2007, 2008])
print(df1)
print(df2)
merged= pd.merge(df1,df2)

print(merged)

      HPI  Int_Rate  IND_GDP
2001   80         2       50
2002   90         1       45
2003   70         2       45
2004   60         3       67
      HPI  Int_Rate  IND_GDP
2005   80         2       50
2006   90         1       45
2007   70         2       45
2008   60         3       67
   HPI  Int_Rate  IND_GDP
0   80         2       50
1   90         1       45
2   70         2       45
3   60         3       67


In [68]:
df_a

subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5      Ayong   Atiches

In [69]:
df_a.append(df_b)

subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5      Ayong   Atiches
0          4      Billy    Bonder
1          5      Brian     Black
2          6       Bran   Balwner
3          7      Bryce     Brice
4          8      Betty    Btisan

In [70]:
df1= pd.DataFrame({ "HPI":[80,90,70,60],"Int_Rate":[2,1,2,3],"IND_GDP":[50,45,45,67]}, index=[2001, 2002, 2003, 2004])

df2=pd.DataFrame({ "HPI":[80,90,70,60],"Int_Rate":[2,1,2,3],"IND_GDP":[50,45,45,67]}, index=[2005, 2006, 2007, 2008])
print(df1)
print(df2)
merged= pd.merge(df1,df2)

print(merged)

      HPI  Int_Rate  IND_GDP
2001   80         2       50
2002   90         1       45
2003   70         2       45
2004   60         3       67
      HPI  Int_Rate  IND_GDP
2005   80         2       50
2006   90         1       45
2007   70         2       45
2008   60         3       67
   HPI  Int_Rate  IND_GDP
0   80         2       50
1   90         1       45
2   70         2       45
3   60         3       67


In [71]:
merged= pd.merge(df1,df2,on ="Int_Rate")

print(merged)

   HPI_x  Int_Rate  IND_GDP_x  HPI_y  IND_GDP_y
0     80         2         50     80         50
1     80         2         50     70         45
2     70         2         45     80         50
3     70         2         45     70         45
4     90         1         45     90         45
5     60         3         67     60         67


In [72]:
#join operation works join on index

df1 = pd.DataFrame({"Int_Rate":[2,1,2,3], "IND_GDP":[50,45,45,67]}, index=[2001, 2002, 2003, 2004])

df2 = pd.DataFrame({"Low_Tier_HPI":[50,45,67,34],"Unemployment":[1,3,5,6]}, index=[2001, 2003, 2004, 2004])

joined= df1.join(df2)
print(joined)

      Int_Rate  IND_GDP  Low_Tier_HPI  Unemployment
2001         2       50          50.0           1.0
2002         1       45           NaN           NaN
2003         2       45          45.0           3.0
2004         3       67          67.0           5.0
2004         3       67          34.0           6.0


In [73]:
df1 = pd.DataFrame({"HPI":[80,90,70,60],"Int_Rate":[2,1,2,3], "IND_GDP":[50,45,45,67]}, index=[2001, 2002,2003,2004])

df2 = pd.DataFrame({"HPI":[80,90,70,60],"Int_Rate":[2,1,2,3],"IND_GDP":[50,45,45,67]}, index=[2005, 2006,2007,2008])

   #axis =0 --> rows  (default)    axis= 1-----> columns
concat= pd.concat([df1,df2])
    
print(concat)

      HPI  Int_Rate  IND_GDP
2001   80         2       50
2002   90         1       45
2003   70         2       45
2004   60         3       67
2005   80         2       50
2006   90         1       45
2007   70         2       45
2008   60         3       67
