In [1]:
import numpy as np

Statistical function with numpy-Mean, median, min, max, ntp, variance, standard deviation

In [2]:
a=np.array([[3,7,5],[8,4,3,],[2,4,9]])

In [3]:
print('our array is ')
print(a)

our array is 
[[3 7 5]
 [8 4 3]
 [2 4 9]]


amin function np.amin(array.axis=0)---->
0--->columns up.amin(array.axis=1)---->axis=1<<<-row

In [4]:
print(np.amin(a,1))

[3 3 2]


In [5]:
# axis=0----> column

print(np.amin(a,0))

[2 4 3]


In [6]:
print(np.amin(a,1))

[3 3 2]


In [7]:
print(np.amax(a,0))

[8 7 9]


In [8]:
a

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

peek to peek = max(a)-min(a)

In [9]:
np.ptp(a)

7

In [10]:
np.ptp(a,axis=0)  # columns

array([6, 3, 6])

In [11]:
np.ptp(a,axis=1)#row

array([4, 5, 7])

In [12]:
#mean function a

a=np.array([[30,65,70],[80,95,10],[50,90,60]])
a

array([[30, 65, 70],
       [80, 95, 10],
       [50, 90, 60]])

In [13]:
np.mean(a)

61.111111111111114

In [14]:
np.mean(a,axis=0)

array([53.33333333, 83.33333333, 46.66666667])

In [15]:
np.mean(a,axis=1)

array([55.        , 61.66666667, 66.66666667])

MEDIAN

In [16]:
a

array([[30, 65, 70],
       [80, 95, 10],
       [50, 90, 60]])

In [17]:
np.median(a)

65.0

In [18]:
np.median(a,axis=0)

array([50., 90., 60.])

In [19]:
np.median(a,axis=1)

array([65., 80., 60.])

In [20]:
np.var(a)

682.0987654320987

In [21]:
np.var(a,axis=0)

array([422.22222222, 172.22222222, 688.88888889])

In [22]:
np.var(a,axis=1)

array([ 316.66666667, 1372.22222222,  288.88888889])

In [23]:
np.std(a)

26.117020607873684

In [24]:
np.std(a,axis=0)

array([20.54804668, 13.12334646, 26.24669291])

In [25]:
np.std(a,axis=1)

array([17.79513042, 37.04351795, 16.99673171])

In [26]:
d3 = np.array([np.nan,1,2,3,np.nan,6,7,8])
d3

array([nan,  1.,  2.,  3., nan,  6.,  7.,  8.])